site_name: Maker Universe
repo_url: "https://github.com/makeruniverse/docs"
edit_uri: edit/main/docs/
theme:
  name: material
  logo: ./_assets/logo.png
  favicon: ./_assets/favicon.ico
  features:
    - content.action.edit
    - content.action.view
    - content.code.copy

    - search.suggest
    - search.highlight
    - search.share

    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    # navigation.expand
    - navigation.path
    # - navigation.footer
    - toc.integrate

  font:
    text: Open Sans

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb 
        name: Switch to dark mode
      primary: orange
      accent: red
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
      primary: orange
      accent: red

  icon:
    edit: material/pencil 
    view: material/eye
    repo: fontawesome/brands/git-alt

extra:
  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@hpi-makeruniverse
    - icon: fontawesome/brands/slack 
      link: https://hpi-makeruniverse.slack.com
    - icon: fontawesome/brands/linkedin 
      link: https://de.linkedin.com/company/makeruniverse
    - icon: fontawesome/brands/instagram 
      link: https://www.instagram.com/hpimakeruniverse

plugins:
  - search
  - offline

markdown_extensions:
  - attr_list
  - admonition

nav:
  - 'Start': 'index.md'
  - 'Tools': 'tools.md'
